apiVersion: v1
kind: Pod
metadata:
  name: cpu-burn-low
  labels:
    load: low
spec:
  containers:
    - name: cpu
      image: progrium/stress
      args: ["--cpu", "1"]
      resources:
        requests:
          cpu: "100m"
        limits:
          cpu: "200m"
