apiVersion: v1
kind: Pod
metadata:
  name: cpu-burn-high
  labels:
    load: high
spec:
  containers:
    - name: cpu
      image: progrium/stress
      args: ["--cpu", "2"]
      resources:
        requests:
          cpu: "200m"
        limits:
          cpu: "400m"
