adminPassword: admin
service:
  type: NodePort
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server
        isDefault: true
dashboards:
  default:
    carbon:
      file: /etc/grafana/provisioning/dashboards/carbon_dashboard.json